export function formatReviewSummary(patternReview) {
  const feedbackSuffix = patternReview.feedbackSummary?.overrides
    ? `, feedback overrides: ${patternReview.feedbackSummary.overrides}`
    : "";
  return `generate: ${patternReview.summary.generate}, review: ${patternReview.summary.review}, skip: ${patternReview.summary.skip}${feedbackSuffix}`;
}

function formatSkippedAutoGeneratedSkills(result) {
  return result.skipped ? " (project-local drafts already up to date)" : "";
}

export function formatProjectScanGenerationSummary({ scanResult, generationResult }) {
  return `patterns: ${scanResult.patterns.patterns.length}, ${formatReviewSummary(scanResult.patternReview)}, generated project-local skills: ${generationResult.generatedSkillNames.length} (created ${generationResult.createdSkillNames.length}, updated ${generationResult.updatedSkillNames.length}, unchanged ${generationResult.unchangedSkillNames.length}, removed ${generationResult.removedSkillNames.length})${formatSkippedAutoGeneratedSkills(generationResult)}`;
}

export function formatProjectScanOnlyMessage({ projectRoot, scanResult, generationResult }) {
  return `Scanned project only: ${projectRoot}, ${formatProjectScanGenerationSummary({ scanResult, generationResult })}.`;
}

export function formatInitScanSuffix({ scanResult, generationResult }) {
  return `, ${formatProjectScanGenerationSummary({ scanResult, generationResult })}`;
}

export function formatInitializedProjectMessage({ projectRoot, selectionSummary, scanSummary }) {
  return `Initialized project AI skills: ${projectRoot}, ${selectionSummary}${scanSummary}.`;
}

export function formatSyncedProjectMessage({ projectRoot, selectionSummary }) {
  return `Synced project AI skills: ${projectRoot}, ${selectionSummary}.`;
}

export function formatScanProjectMessage({ projectRoot, result }) {
  return `Scanned project: ${projectRoot}, view files: ${result.projectProfile.fileSummary.viewFileCount}, patterns: ${result.patterns.patterns.length}, ${formatReviewSummary(result.patternReview)}, diff: added ${result.patternDiff.summary.added}, changed ${result.patternDiff.summary.changed}, removed ${result.patternDiff.summary.removed}.`;
}

export function formatDiffProjectScanMessage({ projectRoot, result }) {
  return `Project scan diff: ${projectRoot}, added: ${result.patternDiff.summary.added}, changed: ${result.patternDiff.summary.changed}, removed: ${result.patternDiff.summary.removed}, unchanged: ${result.patternDiff.summary.unchanged}.`;
}

export function formatGenerateProjectLocalSkillsMessage({ projectRoot, result }) {
  return `Generated project-local skills: ${projectRoot}, skills: ${result.generatedSkillNames.length}, created: ${result.createdSkillNames.length}, updated: ${result.updatedSkillNames.length}, unchanged: ${result.unchangedSkillNames.length}, removed: ${result.removedSkillNames.length}, ${formatReviewSummary(result.patternReview)}${formatSkippedAutoGeneratedSkills(result)}.`;
}

export function formatListProjectLocalSkillsMessage({ projectRoot, result }) {
  const manualNames = result.manualSkills.map((item) => item.name).join(", ") || "none";
  const autoGeneratedNames = result.autoGeneratedSkills.map((item) => item.name).join(", ") || "none";
  return `Project-local skills: ${projectRoot}, manual: ${result.manualSkills.length} [${manualNames}], auto-generated: ${result.autoGeneratedSkills.length} [${autoGeneratedNames}].`;
}

export function formatPromoteProjectLocalSkillMessage(result) {
  return `Promoted project-local skill: ${result.skillName}, target: ${result.targetRoot}.`;
}

export function formatPlanProjectLocalPromotionsMessage({ projectRoot, result }) {
  const eligibleNames = result.candidates.filter((item) => item.status === "eligible").map((item) => item.skillName).join(", ") || "none";
  const blockedNames = result.candidates.filter((item) => item.status === "blocked").map((item) => item.skillName).join(", ") || "none";
  const requestedSuffix = result.requestedSkillName ? `, requested: ${result.requestedSkillName}` : "";
  return `Project-local promotion plan: ${projectRoot}${requestedSuffix}, eligible: ${result.summary.eligibleCount} [${eligibleNames}], blocked: ${result.summary.blockedCount} [${blockedNames}]. Confirm an eligible draft with \`${result.manualConfirmation.commandTemplate}\`.`;
}

export function formatReviewProjectPatternMessage(result) {
  return result.cleared
    ? `Cleared project pattern feedback: ${result.patternType}, feedback: ${result.patternFeedbackPath}.`
    : `Reviewed project pattern: ${result.patternType}, decision: ${result.decision}, feedback: ${result.patternFeedbackPath}.`;
}

export function formatCaptureSessionMessage({ projectRoot, result }) {
  return `Captured session summaries: ${projectRoot}, records: ${result.recordsAdded}, skipped: ${result.skippedRecords}, ask: ${result.evaluation.summary.askCapture}, review: ${result.evaluation.summary.askReview || 0}, duplicate: ${result.evaluation.summary.skipDuplicate}, covered: ${result.evaluation.summary.skipAlreadyCovered}, irrelevant: ${result.evaluation.summary.skipIrrelevant}.`;
}

export function formatAutoCaptureSkippedMessage({ projectRoot, result }) {
  if (result.autoCaptureDecision === "review_required") {
    return `Auto capture requires manual confirmation: ${projectRoot}, review records: ${result.reviewBoundary?.reviewRequiredCount || 0}, capture-ready records: ${result.reviewBoundary?.captureReadyCount || 0}. Use prepare/confirm capture or a wrapper capture command so review-level records are explicitly acknowledged.`;
  }
  return `Auto capture skipped: ${projectRoot}, overallDecision: ${result.overallDecision}, ask: ${result.summary.askCapture}, review: ${result.summary.askReview || 0}, duplicate: ${result.summary.skipDuplicate}, covered: ${result.summary.skipAlreadyCovered}, irrelevant: ${result.summary.skipIrrelevant}.`;
}

export function formatAutoCaptureSubmittedMessage(result) {
  return result.consumed
    ? `Auto capture submitted and consumed: ${result.requestId}, processed: ${result.consumed.processedCount}, failed: ${result.consumed.failedCount}.`
    : `Auto capture submitted: ${result.requestId}, queue: ${result.queueFilePath}.`;
}

export function formatQueuedAutoCaptureResponseMessage(result) {
  return result.consumed
    ? `Queued and consumed auto-capture response: ${result.requestId}, processed: ${result.consumed.processedCount}, failed: ${result.consumed.failedCount}.`
    : `Queued auto-capture response: ${result.requestId}, queue: ${result.queueFilePath}.`;
}

export function formatConfirmSessionCaptureMessage(result) {
  return result.status === "rejected"
    ? `Rejected pending session capture: ${result.requestId}.`
    : `Confirmed session capture: ${result.requestId}, records: ${result.recordsAdded}.`;
}

export function formatConsumeAutoCaptureInboxMessage({ projectRoot, result, requestId }) {
  return `Consumed auto-capture inbox: ${projectRoot}, processed: ${result.processedCount}, failed: ${result.failedCount}${requestId ? `, request: ${requestId}` : ""}.`;
}

export function formatConsumeAutoCaptureResponseInboxMessage({ projectRoot, result, requestId }) {
  return `Consumed auto-capture response inbox: ${projectRoot}, processed: ${result.processedCount}, failed: ${result.failedCount}${requestId ? `, request: ${requestId}` : ""}.`;
}

export function formatWatchAutoCaptureInboxMessage({ projectRoot, pollIntervalMs, maxItems }) {
  return `Watching auto-capture inbox: ${projectRoot}, pollIntervalMs: ${pollIntervalMs || "default"}, maxItems: ${maxItems || "default"}.`;
}

export function formatToolCaptureSkippedMessage({ displayName, projectRoot, prepared }) {
  return `${displayName} capture skipped: ${projectRoot}, overallDecision: ${prepared.overallDecision}, ask: ${prepared.summary.askCapture}, review: ${prepared.summary.askReview || 0}, duplicate: ${prepared.summary.skipDuplicate}, covered: ${prepared.summary.skipAlreadyCovered}, irrelevant: ${prepared.summary.skipIrrelevant}.`;
}

export function formatToolCaptureDecisionMessage({ displayName, decision, prepared, resolved }) {
  return decision === "captured"
    ? `${displayName} capture confirmed: ${prepared.requestId}, records: ${resolved.recordsAdded}.`
    : `${displayName} capture rejected: ${prepared.requestId}.`;
}

export function formatAnalyzePatternsMessage({ projectRoot, result }) {
  return `Analyzed conversation patterns: ${projectRoot}, records: ${result.summary.recordCount}, patterns: ${result.patterns.length}, generate: ${result.summary.generate}, review: ${result.summary.review}, skip: ${result.summary.skip}.`;
}

export function formatReviewConversationPatternMessage(result) {
  if (result.mode === "batch") {
    return `Reviewed conversation patterns in batch: source ${result.sourceDecision}, applied ${result.appliedDecision}, processed: ${result.processedCount}, skipped: ${result.skippedCount}, report: ${result.reportPath}.`;
  }
  return `Reviewed conversation pattern: ${result.patternId}, decision: ${result.decision}, target: ${result.target || "none"}, report: ${result.reportPath}.`;
}

export function formatMergeConversationPatternMessage(result) {
  return `Merged conversation pattern: ${result.sourcePatternId} -> ${result.targetPatternId}, governance: ${result.patternGovernancePath}.`;
}

export function formatArchiveConversationPatternMessage(result) {
  return `Archived conversation pattern: ${result.patternId}, governance: ${result.patternGovernancePath}.`;
}

export function formatRestoreConversationPatternMessage(result) {
  return `Restored conversation pattern: ${result.patternId}, restored rules: ${result.restoredTypes.join(", ")}.`;
}

export function formatGenerateProjectSkillMessage(result) {
  if (result.skipped) {
    return `Conversation-mined project skill already up to date: ${result.skillName}, pattern: ${result.patternId}, target: ${result.skillRoot}.`;
  }
  return `Generated conversation-mined project skill: ${result.skillName}, pattern: ${result.patternId}, target: ${result.skillRoot}.`;
}

export function formatScaffoldWrapperPromotionMessage(result) {
  return `Scaffolded wrapper promotion proposal: ${result.toolName}, style: ${result.integrationStyle}, target: ${result.promotionRoot}.`;
}

export function formatListWrapperPromotionsMessage({ projectRoot, result }) {
  const summary = result.proposals.map((item) => `${item.toolName}:${item.status}`).join(", ") || "none";
  return `Wrapper promotions: ${projectRoot}, count: ${result.count}, items: ${summary}.`;
}

export function formatShowWrapperPromotionTimelineMessage(result) {
  return `Wrapper promotion timeline: ${result.toolName}, steps: ${result.timeline.length}, archived: ${result.archived}.`;
}

export function formatGenerateWrapperPromotionAuditMessage(result) {
  return `Generated wrapper promotion audit: ${result.reportPath}, total: ${result.summary.total}, active: ${result.summary.active}, archived: ${result.summary.archived}${result.exportPath ? `, export: ${result.exportPath}` : ""}.`;
}

export function formatGenerateWrapperRegistryGovernanceMessage(result) {
  return `Generated wrapper registry governance: ${result.reportPath}, registered wrappers: ${result.summary.registeredWrapperCount}, proposals: ${result.summary.proposalCount}, ready: ${result.summary.readyForRegistration}, stalled: ${result.summary.stalledProposalCount}.`;
}

export function formatPlanWrapperRegistrationsMessage(result) {
  const eligibleNames = result.candidates.filter((item) => item.status === "eligible").map((item) => item.toolName).join(", ") || "none";
  const blockedNames = result.candidates.filter((item) => item.status === "blocked").map((item) => item.toolName).join(", ") || "none";
  const requestedSuffix = result.requestedToolName ? `, tool: ${result.requestedToolName}` : "";
  return `Wrapper registration plan${requestedSuffix}, target registry: ${result.summary.targetRegistryPath}, eligible: ${result.summary.eligibleCount} [${eligibleNames}], blocked: ${result.summary.blockedCount} [${blockedNames}]. Register an eligible proposal with \`${result.manualConfirmation.commandTemplate}\`.`;
}

export function formatGenerateUpgradeSummaryMessage(result) {
  return `Generated upgrade summary: ${result.reportPath}, mode: ${result.mode}, status: ${result.status}, actions: ${result.recommendedActions.length}.`;
}

function formatLatestControlledExecutionSummary(publishExecutionSummary) {
  if (!publishExecutionSummary) {
    return "latest controlled execution: none";
  }
  const recordLabel = publishExecutionSummary.recordPathRelative || publishExecutionSummary.recordPath || "record unavailable";
  const failureSummaryLabel = publishExecutionSummary.failureSummaryPathRelative || publishExecutionSummary.failureSummaryPath || null;
  const failureSummarySuffix = failureSummaryLabel ? `, failure summary: ${failureSummaryLabel}` : "";
  return `latest controlled execution: ${publishExecutionSummary.status} (record: ${recordLabel}${failureSummarySuffix})`;
}

function formatNextActionSummary(nextAction) {
  if (!nextAction) {
    return "next action: review the latest release evidence manually";
  }
  if (nextAction.command) {
    return `next action: \`${nextAction.command}\``;
  }
  if (nextAction.kind === "publish-complete") {
    return `next action: ${nextAction.reason}`;
  }
  if (nextAction.kind === "controlled-gate-satisfied" && nextAction.manualPublishCommand) {
    return `next action: ${nextAction.reason}`;
  }
  return `next action: ${nextAction.reason}`;
}

export function formatPlanReleasePublishMessage(result) {
  const registryLabel = result.targetPublish.registryUrl || "missing";
  const latestExecutionSummary = formatLatestControlledExecutionSummary(result.evidence?.publishExecutionSummary || null);
  const nextActionSummary = formatNextActionSummary(result.nextAction);
  return `Release publish plan: ${result.targetPublish.packageName}@${result.targetPublish.version}, status: ${result.status}, registry: ${registryLabel}, blockers: ${result.blockers.length}, ${latestExecutionSummary}, ${nextActionSummary}. Refresh evidence with \`${result.manualConfirmation.refreshArtifactsCommand}\`, validate with \`${result.manualConfirmation.releaseCheckCommand}\` and \`${result.manualConfirmation.releaseGenerateCommand}\`, then advance through the controlled executor.`;
}

export function formatExecuteReleasePublishMessage(result) {
  const registryLabel = result.targetPublish.registryUrl || "missing";
  const recordLabel = result.executionRecordPathRelative || result.manifestArtifacts?.recordPathRelative || "manifest/release-publish-record.json";
  const failureSummaryLabel = result.failureSummaryPathRelative || result.manifestArtifacts?.failureSummaryPathRelative || "none";
  const nextActionSummary = formatNextActionSummary(result.nextAction);
  return `Release publish execution: ${result.targetPublish.packageName}@${result.targetPublish.version}, status: ${result.status}, registry: ${registryLabel}, confirm: ${result.commandFlags.confirm}, acknowledgeWarnings: ${result.commandFlags.acknowledgeWarnings}, publishAttempted: ${result.publishAttempted}, record: ${recordLabel}, failure summary: ${failureSummaryLabel}, ${nextActionSummary}. Next command target: \`${result.wouldExecuteCommand}\`.`;
}

export function formatPlanReleaseOrchestrationMessage(result) {
  const stageSummary = result.stages.map((item) => `${item.id}:${item.status}`).join(", ") || "none";
  const nextActionSummary = formatNextActionSummary(result.nextAction);
  return `Release orchestration plan: status ${result.status}, stages: ${result.stages.length} [${stageSummary}], blockers: ${result.blockers.length}, ${nextActionSummary}. Controlled publish remains anchored on \`execute-release-publish\`; this planner is dry-run only.`;
}

export function formatGenerateGovernanceSummaryMessage(result) {
  return `Generated governance summary: ${result.reportPath}, status: ${result.status}, overdue reviews: ${result.summary.overdueGovernanceReviews}, pending conversation reviews: ${result.summary.pendingConversationReviews}, pending wrapper proposals: ${result.summary.pendingWrapperProposals}.`;
}

export function formatRunEvolutionCycleMessage(result) {
  return `Ran evolution cycle: ${result.reportPath}, status: ${result.status}, triggered: ${result.triggered}, reason: ${result.triggerReason}, new conversations: ${result.metrics.newConversationCount}/${result.thresholds.minNewConversations}.`;
}

export function formatShowEvolutionPolicyMessage(result) {
  return `Loaded evolution policy: ${result.policyPath}, source: ${result.source}, auto analyze: ${result.policy.autoAnalyzeEnabled}, threshold: ${result.policy.minConversationCountToAnalyze}, validation ok: ${result.validation.ok}.`;
}

export function formatValidateEvolutionPolicyMessage(result) {
  return `Validated evolution policy: ok ${result.ok}, errors ${result.summary.errorCount}, warnings ${result.summary.warningCount}, min conversations: ${result.summary.minConversationCountToAnalyze}.`;
}

export function formatGenerateEvolutionCandidatesMessage(result) {
  return `Generated evolution candidates: ${result.reportPath}, total: ${result.summary.total}, review: ${result.summary.review}, high risk: ${result.summary.highRisk}, profile adjustments: ${result.summary.profileAdjustmentCandidates}.`;
}

export function formatApplyEvolutionActionsMessage(result) {
  return `Applied evolution actions: ${result.actionsPath}, total: ${result.summary.total}, executed: ${result.summary.executed}, skipped: ${result.summary.skipped}, failed: ${result.summary.failed}.`;
}

export function formatGenerateEvolutionProposalsMessage(result) {
  return `Generated evolution proposals: ${result.reportPath}, total: ${result.summary.total}, review: ${result.summary.review}, high risk: ${result.summary.highRisk}, profile adjustments: ${result.summary.profileAdjustments}.`;
}

export function formatListEvolutionProposalsMessage(result) {
  return `Listed evolution proposals: ${result.proposalsPath}, returned: ${result.summary.returned}/${result.summary.total}, review: ${result.summary.review}, archived included: ${result.summary.includeArchived}, limit: ${result.summary.limit || "none"}.`;
}

export function formatListEvolutionDraftsMessage(result) {
  return `Listed evolution drafts: ${result.proposalsPath}, returned: ${result.summary.returned}/${result.summary.total}, pending follow-ups: ${result.summary.pendingFollowUps}, limit: ${result.summary.limit || "none"}.`;
}

export function formatShowEvolutionDraftMessage(result) {
  return `Loaded evolution draft: ${result.draft.draftId}, type: ${result.draft.artifactType}, proposal: ${result.proposalId}, next actions: ${result.draft.followUpActionCount}.`;
}

export function formatPlanSharedSkillPromotionsMessage(result) {
  const eligibleNames = result.candidates.filter((item) => item.status === "eligible").map((item) => item.skillName).join(", ") || "none";
  const blockedNames = result.candidates.filter((item) => item.status === "blocked").map((item) => item.skillName || item.draftId).join(", ") || "none";
  const requestedDraftSuffix = result.requestedDraftId ? `, draft: ${result.requestedDraftId}` : "";
  const requestedProposalSuffix = result.requestedProposalId ? `, proposal: ${result.requestedProposalId}` : "";
  const requestedSkillSuffix = result.requestedSkillName ? `, skill: ${result.requestedSkillName}` : "";
  return `Shared skill promotion plan: ${result.packageRoot}${requestedDraftSuffix}${requestedProposalSuffix}${requestedSkillSuffix}, eligible: ${result.summary.eligibleCount} [${eligibleNames}], blocked: ${result.summary.blockedCount} [${blockedNames}]. Manual catalog writes remain required; scaffold with \`${result.manualConfirmation.commandTemplate}\` and validate with \`${result.manualConfirmation.validationCommand}\`.`;
}

export function formatReviewEvolutionProposalMessage(result) {
  if (result.mode === "batch") {
    return `Reviewed evolution proposals in batch: source ${result.sourceStatus || "all"}, type: ${result.proposalType || "all"}, decision: ${result.decision}, processed: ${result.processedCount}, skipped: ${result.skippedCount}, report: ${result.reportPath}.`;
  }
  return `Reviewed evolution proposal: ${result.proposalId}, decision: ${result.decision}, report: ${result.reportPath}.`;
}

export function formatApplyEvolutionProposalMessage(result) {
  if (result.mode === "batch") {
    return `Applied evolution proposals in batch: source ${result.sourceStatus || "all"}, type: ${result.proposalType || "all"}, processed: ${result.processedCount}, skipped: ${result.skippedCount}, report: ${result.reportPath}.`;
  }
  return `Applied evolution proposal: ${result.proposalId}, decision: ${result.decision}, report: ${result.reportPath}.`;
}

export function formatShowGovernanceHistoryMessage(result) {
  return `Loaded governance history: ${result.reportPath}, type: ${result.summary.requestedType}, returned entries: ${result.summary.returnedEntries}/${result.summary.totalEntries}.`;
}

export function formatGenerateConversationMinerStrategyMessage(result) {
  return `Generated conversation miner strategy: ${result.configPath}, type: ${result.projectType}, dryRun: ${result.dryRun}, changed: ${result.changed}.`;
}

export function formatCheckAutoCaptureRuntimeMessage(result) {
  return `Checked auto-capture runtime: ${result.reportPath}, status: ${result.status}, enabled: ${result.summary.autoCaptureEnabled}, activity: ${result.summary.activityState}, capture backlog: ${result.summary.captureBacklogCount}, response backlog: ${result.summary.responseBacklogCount}, failed: ${result.summary.failedRequestCount}.`;
}

export function formatShowAutoCaptureBridgeContractMessage(result) {
  return `Loaded auto-capture bridge contract: ${result.contractPath}, tools: ${result.tools.length}, runtime enabled: ${result.runtime.enabled}, response inbox: ${result.sharedPaths.responseInboxPath}.`;
}

export function formatShowCaptureSafetyPolicyMessage(result) {
  return `Loaded capture safety policy: ${result.policyPath}, enabled: ${result.policy.enabled}, allowed scenes: ${result.validation.summary.allowedSceneTypeCount}, review scenes: ${result.validation.summary.reviewSceneTypeCount}, blocked scene types: ${result.validation.summary.blockedSceneTypeCount}, blocked keywords: ${result.validation.summary.blockedKeywordCount}, review keywords: ${result.validation.summary.reviewKeywordCount}, blocked file patterns: ${result.validation.summary.blockedFilePatternCount || 0}, review file patterns: ${result.validation.summary.reviewFilePatternCount || 0}, validation ok: ${result.validation.ok}.`;
}

export function formatValidateCaptureSafetyPolicyMessage(result) {
  return `Validated capture safety policy: ok ${result.ok}, errors ${result.summary.errorCount}, warnings ${result.summary.warningCount}, allowed scenes: ${result.summary.allowedSceneTypeCount}, review scenes: ${result.summary.reviewSceneTypeCount}, blocked scene types: ${result.summary.blockedSceneTypeCount}, blocked keywords: ${result.summary.blockedKeywordCount}, review keywords: ${result.summary.reviewKeywordCount}, blocked file patterns: ${result.summary.blockedFilePatternCount || 0}, review file patterns: ${result.summary.reviewFilePatternCount || 0}.`;
}

export function formatCheckCaptureRetentionMessage(result) {
  return `Checked capture retention: ${result.reportPath}, status: ${result.status}, active files: ${result.summary.activeFileCount}, archived files: ${result.summary.archivedFileCount}, archive candidates: ${result.summary.archiveCandidateCount}, prune candidates: ${result.summary.pruneCandidateCount}.`;
}

export function formatApplyCaptureRetentionMessage(result) {
  return `Applied capture retention: ${result.reportPath}, dryRun: ${result.dryRun}, archived files: ${result.summary.archivedFiles}, pruned files: ${result.summary.prunedFiles}, skipped: ${result.summary.skippedFiles}.`;
}

export function formatCheckProjectBaselineMessage(result) {
  return `Checked project baseline: ${result.reportPath}, status: ${result.status}, checks: ${result.summary.total}, failed: ${result.summary.failed}, warnings: ${result.summary.warnings}.`;
}

export function formatShowTeamPolicyMessage(result) {
  return `Loaded team policy: allowed tools ${result.teamPolicy.allowedTools.length}, default tools ${result.teamPolicy.defaultTools.length}, required skills ${result.teamPolicy.requiredSkills.length}, validation ok: ${result.validation.ok}.`;
}

export function formatValidateTeamPolicyMessage(result) {
  return `Validated team policy: ok ${result.ok}, errors ${result.summary.errorCount}, warnings ${result.summary.warningCount}, project profiles ${result.summary.projectProfileCount}.`;
}

export function formatCheckTeamPolicyDriftMessage(result) {
  return `Checked team policy drift: ${result.reportPath}, status: ${result.status}, checks: ${result.summary.total}, failed: ${result.summary.failed}, warnings: ${result.summary.warnings}.`;
}

export function formatCheckGovernanceReviewDeadlinesMessage(result) {
  return `Checked governance review deadlines: ${result.reportPath}, overdue: ${result.summary.overdueReviews}, due today: ${result.summary.dueTodayReviews}, next review: ${result.summary.nextReviewAt || "none"}.`;
}

export function formatShowProjectProfileDecisionMessage(result) {
  return `Loaded project profile decision: ${result.decision.decisionPath}, decision: ${result.decision.decision}, drift: ${result.decision.driftStatus}, review: ${result.decision.reviewStatus}, history: ${result.historyCount}.`;
}

export function formatReviewProjectProfileMessage(result) {
  if (result.acceptRecommended) {
    return `Reviewed project profile recommendation: accepted recommended profile ${result.acceptedProjectProfile || "none"}, selected: ${result.selectedProjectProfile || "none"}, history: ${result.historyCount}.`;
  }
  return `Reviewed project profile recommendation: decision ${result.decision}, selected: ${result.selectedProjectProfile || "none"}, recommended: ${result.recommendedProjectProfile || "none"}, history: ${result.historyCount}.`;
}

export function formatShowProjectGovernanceContextMessage(result) {
  return `Loaded project governance context: ${result.contextPath}, profile: ${result.selectedProjectProfile || "none"} -> ${result.recommendedProjectProfile || "none"}, baseline: ${result.baselineStatus}, policy drift: ${result.policyDriftStatus}, auto capture: ${result.autoCaptureRuntime?.status || "unknown"}.`;
}

export function formatShowPromotionTraceMessage(result) {
  return `Loaded promotion trace: matches ${result.matchCount}, trace: ${result.tracePath}, report: ${result.reportPath}.`;
}

export function formatReviewWrapperPromotionMessage(result) {
  return `Reviewed wrapper promotion: ${result.toolName}, status: ${result.status}, target: ${result.promotionRoot}.`;
}

export function formatMaterializeWrapperPromotionMessage(result) {
  return `Materialized wrapper promotion: ${result.toolName}, target: ${result.artifactsRoot}.`;
}

export function formatApplyWrapperPromotionMessage(result) {
  if (result.dryRun) {
    return `Dry-run wrapper promotion: ${result.toolName}, would change files: ${result.changedFiles.length}, total writes: ${result.wouldWriteFiles.length}.`;
  }
  return `Applied wrapper promotion: ${result.toolName}, changed files: ${result.changedFiles.length}.`;
}

export function formatFinalizeWrapperPromotionMessage(result) {
  return `Finalized wrapper promotion: ${result.toolName}, status: ${result.followUpStatus}.`;
}

export function formatRegisterWrapperPromotionMessage(result) {
  return `Registered wrapper promotion: ${result.toolName}, status: ${result.registrationStatus}.`;
}

export function formatArchiveWrapperPromotionMessage(result) {
  return `Archived wrapper promotion: ${result.toolName}, status: ${result.archiveStatus}.`;
}

export function formatRestoreWrapperPromotionMessage(result) {
  return `Restored wrapper promotion: ${result.toolName}, status: ${result.archiveStatus}.`;
}

export function formatAddToolMessage({ requestedSelection, selectionSummary }) {
  return `Added tool entrypoints: ${requestedSelection.selectedTools.join(", ")}, ${selectionSummary}.`;
}

export function formatRemoveToolMessage({ requestedSelection, selectionSummary }) {
  return `Removed tool entrypoints: ${requestedSelection.selectedTools.join(", ")}, current ${selectionSummary}.`;
}

export function formatCleanReportsMessage(result) {
  return result.removed
    ? `Removed reports directory: ${result.reportsRoot}`
    : `Reports directory does not exist: ${result.reportsRoot}`;
}
