export function formatRecommendationLabel(recommendation) {
  if (recommendation === "generate") return "generate-project-skill";
  if (recommendation === "review") return "review-project-pattern";
  return "skip";
}

export function buildConversationSkillMarkdown(definition, pattern, generatedAt) {
  const baseSkillPath = `../../../ui/${definition.baseSkill}/SKILL.md`;
  const commonSkills = (pattern.commonSkills || []).map((item) => `- \`${item}\``).join("\n") || "- none";
  const mainObjects = (pattern.mainObjects || []).map((item) => `- \`${item}\``).join("\n") || "- none";
  const treeObjects = (pattern.treeObjects || []).map((item) => `- \`${item}\``).join("\n") || "- none";
  const operations = (pattern.operations || []).map((item) => `- \`${item}\``).join("\n") || "- none";
  const customizations = (pattern.customizations || []).map((item) => `- \`${item}\``).join("\n") || "- none";
  const sampleFiles = (pattern.sampleGeneratedFiles || []).map((item) => `- \`${item}\``).join("\n") || "- none";

  return `---
name: "${definition.skillName}"
description: "${definition.description}"
---

# ${definition.displayName}

This draft was generated by \`power-ai-skills analyze-patterns\` at ${generatedAt}.

## Read Before Implementing

- Base skill: \`${baseSkillPath}\`
- Pattern source: \`.power-ai/patterns/project-patterns.json\`

## Conversation-Mined Signals

- sceneType: \`${pattern.sceneType}\`
- frequency: ${pattern.frequency}
- reuseScore: ${pattern.reuseScore}
- reuseValue: \`${pattern.reuseValue}\`
- recommendation: \`${pattern.recommendation}\`

Common skills:
${commonSkills}

Main objects:
${mainObjects}

Tree objects:
${treeObjects}

Operations:
${operations}

Customizations:
${customizations}

Representative generated files:
${sampleFiles}

## Implementation Rules

1. Reuse the enterprise base skill first.
2. Only add project-specific conventions extracted from repeated conversations.
3. Keep object naming, operations, and customization points aligned with the mined pattern.
4. Treat this file as a draft until a maintainer confirms it.
`;
}

export function buildConversationReferenceMarkdown(pattern) {
  const sampleConversationIds = (pattern.sampleConversationIds || []).map((item) => `- \`${item}\``).join("\n") || "- none";
  const generatedFiles = (pattern.sampleGeneratedFiles || []).map((item) => `- \`${item}\``).join("\n") || "- none";
  return `# Conversation Miner References

- pattern id: \`${pattern.id}\`
- sceneType: \`${pattern.sceneType}\`
- frequency: ${pattern.frequency}
- recommendation: \`${pattern.recommendation}\`

## Sample Conversations

${sampleConversationIds}

## Sample Generated Files

${generatedFiles}
`;
}

export function buildPatternSummaryMarkdown({ projectName, payload }) {
  const lines = [
    "# Conversation Pattern Summary",
    "",
    `- project: \`${projectName}\``,
    `- lastAnalyzed: \`${payload.lastAnalyzed}\``,
    `- conversation files: ${payload.summary.fileCount}`,
    `- conversation records: ${payload.summary.recordCount}`,
    `- generated patterns: ${payload.summary.generate}`,
    `- review patterns: ${payload.summary.review}`,
    `- skipped patterns: ${payload.summary.skip}`,
    "",
    "## Patterns",
    ""
  ];

  if ((payload.patterns || []).length === 0) {
    lines.push("No conversation patterns detected.");
    lines.push("");
    return `${lines.join("\n")}\n`;
  }

  for (const pattern of payload.patterns) {
    lines.push(`### ${pattern.sceneType}`);
    lines.push("");
    lines.push(`- id: \`${pattern.id}\``);
    lines.push(`- frequency: ${pattern.frequency}`);
    lines.push(`- reuseScore: ${pattern.reuseScore}`);
    lines.push(`- recommendation: \`${pattern.recommendation}\``);
    lines.push(`- candidateSkill: \`${pattern.candidateSkill?.name || "none"}\``);
    lines.push("");
  }

  return `${lines.join("\n")}\n`;
}

export function buildCaptureEvaluationReportMarkdown({ projectName, payload }) {
  const lines = [
    "# Session Capture Evaluation",
    "",
    `- project: \`${projectName}\``,
    `- evaluatedAt: \`${payload.evaluatedAt}\``,
    `- sourceType: \`${payload.source?.type || "unknown"}\``,
    `- sourcePath: \`${payload.source?.path || "unknown"}\``,
    `- extractedMarkedBlock: ${payload.source?.extractedMarkedBlock ? "yes" : "no"}`,
    `- overallDecision: \`${payload.overallDecision}\``,
    `- askCapture: ${payload.summary.askCapture}`,
    `- askReview: ${payload.summary.askReview || 0}`,
    `- askWarning: ${payload.summary.askWarning || 0}`,
    `- skipIrrelevant: ${payload.summary.skipIrrelevant}`,
    `- skipIncomplete: ${payload.summary.skipIncomplete}`,
    `- skipSensitive: ${payload.summary.skipSensitive || 0}`,
    `- skipPolicyFiltered: ${payload.summary.skipPolicyFiltered || 0}`,
    `- skipLowValue: ${payload.summary.skipLowValue}`,
    `- skipDuplicate: ${payload.summary.skipDuplicate}`,
    `- skipAlreadyCovered: ${payload.summary.skipAlreadyCovered}`,
    `- governance warning: ${payload.captureSafetyGovernance?.summary?.warning || 0}`,
    `- governance review: ${payload.captureSafetyGovernance?.summary?.review || 0}`,
    `- governance blocking: ${payload.captureSafetyGovernance?.summary?.blocking || 0}`,
    "",
    "## Records",
    ""
  ];

  if ((payload.evaluations || []).length === 0) {
    lines.push("No session summaries were evaluated.");
    lines.push("");
    return `${lines.join("\n")}\n`;
  }

  for (const evaluation of payload.evaluations) {
    lines.push(`### ${evaluation.record.id}`);
    lines.push("");
    lines.push(`- decision: \`${evaluation.decision}\``);
    lines.push(`- admissionLevel: \`${evaluation.admissionLevel || "capture"}\``);
    lines.push(`- governanceLevel: \`${evaluation.captureSafetyGovernanceLevel || "none"}\``);
    lines.push(`- score: ${evaluation.score}`);
    lines.push(`- sceneType: \`${evaluation.record.sceneType || "unknown"}\``);
    lines.push(`- reasons: ${evaluation.reasons.length > 0 ? evaluation.reasons.map((item) => `\`${item}\``).join(", ") : "none"}`);
    if ((evaluation.captureSafetyGovernanceReasons || []).length > 0) lines.push(`- governanceReasons: ${evaluation.captureSafetyGovernanceReasons.map((item) => `\`${item}\``).join(", ")}`);
    if (evaluation.coveredBySkills.length > 0) lines.push(`- coveredBySkills: ${evaluation.coveredBySkills.map((item) => `\`${item}\``).join(", ")}`);
    lines.push("");
  }

  return `${lines.join("\n")}\n`;
}

export function buildPendingCapturePrompt(summary) {
  return `检测到 ${summary.askCapture} 条值得沉淀的会话摘要，是否确认收集到 conversation-miner？`;
}
