/**
 * Upgrade Summary Collectors 模块
 * 
 * 负责：
 * - 收集项目扫描信息
 * - 收集对话挖掘信息
 * - 收集提升追踪信息
 * - 收集治理上下文信息
 * - 收集包装提升信息
 * - 收集发布治理信息
 */

import fs from "node:fs";
import path from "node:path";
import { readJson } from "../shared/fs.mjs";

/**
 * 读取 JSON 文件（如果存在）
 */
function readJsonIfExists(filePath) {
  return filePath && fs.existsSync(filePath) ? readJson(filePath) : null;
}

function pickHigherRiskLevel(...levels) {
  const weights = { low: 1, medium: 2, high: 3 };
  return levels
    .filter((level) => typeof level === "string" && weights[level])
    .sort((left, right) => weights[right] - weights[left])[0] || "";
}

/**
 * 统计项目级技能目录数量
 */
function countProjectLocalSkillDirectories(rootDir) {
  if (!rootDir || !fs.existsSync(rootDir)) return 0;
  return fs.readdirSync(rootDir, { withFileTypes: true }).filter((entry) => entry.isDirectory()).length;
}

/**
 * 收集项目扫描部分
 */
export function collectProjectScanSection(projectRoot, projectScanService) {
  try {
    const artifacts = projectScanService.loadAnalysisArtifacts();
    const skillsRoot = path.join(projectRoot, ".power-ai", "skills", "project-local");
    const autoGeneratedRoot = path.join(skillsRoot, "auto-generated");
    const manualRoot = path.join(skillsRoot, "manual");
    return {
      available: true,
      generatedAt: artifacts.patterns.generatedAt,
      projectName: artifacts.projectProfile.projectName,
      viewFileCount: artifacts.projectProfile.fileSummary?.viewFileCount || 0,
      patternCount: (artifacts.patterns.patterns || []).length,
      reviewSummary: artifacts.patternReview.summary,
      feedbackSummary: artifacts.patternReview.feedbackSummary || {
        overrides: artifacts.patternFeedback?.summary?.total || 0,
        applied: 0,
        stale: 0
      },
      diffSummary: artifacts.patternDiff.summary,
      autoGeneratedSkillCount: countProjectLocalSkillDirectories(autoGeneratedRoot),
      manualSkillCount: countProjectLocalSkillDirectories(manualRoot),
      artifacts: {
        patternsPath: projectScanService.getAnalysisPaths().patternsPath,
        patternReviewPath: projectScanService.getAnalysisPaths().patternReviewPath,
        patternFeedbackPath: projectScanService.getAnalysisPaths().patternFeedbackPath,
        summaryReportPath: projectScanService.getAnalysisPaths().summaryReportPath,
        feedbackReportPath: projectScanService.getAnalysisPaths().feedbackReportPath
      }
    };
  } catch (error) {
    return {
      available: false,
      reason: error.message
    };
  }
}

/**
 * 收集对话挖掘部分
 */
export function collectConversationSection(conversationMinerService) {
  try {
    const { payload, paths } = conversationMinerService.loadProjectPatterns();
    const decisions = conversationMinerService.loadConversationDecisions();
    return {
      available: true,
      generatedAt: payload.lastAnalyzed,
      projectName: payload.projectName,
      summary: payload.summary,
      patternCount: (payload.patterns || []).length,
      decisionSummary: decisions.summary,
      artifacts: {
        projectPatternsPath: paths.projectPatternsPath,
        patternSummaryPath: paths.patternSummaryPath,
        patternGovernancePath: paths.patternGovernancePath,
        patternGovernanceReportPath: paths.patternGovernanceReportPath,
        conversationDecisionsPath: decisions.decisionsPath,
        conversationDecisionHistoryPath: decisions.historyPath,
        conversationDecisionReportPath: decisions.reportPath
      }
    };
  } catch (error) {
    return {
      available: false,
      reason: error.message
    };
  }
}

/**
 * 收集提升追踪部分
 */
export function collectPromotionTraceSection(promotionTraceService) {
  try {
    const result = promotionTraceService.showPromotionTrace();
    return {
      available: true,
      generatedAt: result.generatedAt,
      summary: result.summary,
      matchCount: result.matchCount,
      tracePath: result.tracePath,
      reportPath: result.reportPath
    };
  } catch (error) {
    return {
      available: false,
      reason: error.message
    };
  }
}

/**
 * 收集治理上下文部分
 */
export function collectGovernanceContextSection(governanceContextService) {
  if (!governanceContextService) {
    return {
      available: false,
      reason: "project governance context service is not configured"
    };
  }

  try {
    const payload = governanceContextService.loadProjectGovernanceContext({ refreshIfMissing: true })
      || governanceContextService.showProjectGovernanceContext();
    return {
      available: true,
      generatedAt: payload.generatedAt,
      selectedProjectProfile: payload.selectedProjectProfile || "",
      recommendedProjectProfile: payload.recommendedProjectProfile || "",
      projectProfileDecision: payload.projectProfileDecision || "auto-recommended",
      baselineStatus: payload.baselineStatus || "not-run",
      policyDriftStatus: payload.policyDriftStatus || "unknown",
      pendingConversationReviews: payload.pendingConversationReviews || 0,
      reviewLevelConversationRecords: payload.reviewLevelConversationRecords || 0,
      captureLevelConversationRecords: payload.captureLevelConversationRecords || 0,
      recordsWithAdmissionMetadata: payload.recordsWithAdmissionMetadata || 0,
      warningLevelConversationRecords: payload.warningLevelConversationRecords || 0,
      blockingLevelConversationRecords: payload.blockingLevelConversationRecords || 0,
      recordsWithGovernanceMetadata: payload.recordsWithGovernanceMetadata || 0,
      pendingWrapperProposals: payload.pendingWrapperProposals || 0,
      requiredSkills: payload.requiredSkills || [],
      allowedTools: payload.allowedTools || [],
      conversationMinerStrategy: payload.conversationMinerStrategy || {
        projectType: "",
        displayName: "",
        captureMode: "",
        autoCaptureEnabled: false,
        configPath: "",
        exists: false
      },
      autoCaptureRuntime: payload.autoCaptureRuntime || {
        status: "unknown",
        activityState: "unknown",
        enabled: false,
        captureBacklogCount: 0,
        responseBacklogCount: 0,
        failedRequestCount: 0,
        staleQueuedCaptureCount: 0,
        staleQueuedResponseCount: 0,
        reportPath: "",
        jsonPath: ""
      },
      captureSafetyPolicy: payload.captureSafetyPolicy || {
        exists: false,
        policyPath: "",
        ok: false,
        warningCount: 0,
        allowedSceneTypeCount: 0,
        blockedSceneTypeCount: 0,
        reviewSceneTypeCount: 0,
        blockedKeywordCount: 0,
        reviewKeywordCount: 0,
        blockedFilePatternCount: 0,
        reviewFilePatternCount: 0,
        enabled: false
      },
      captureRetention: payload.captureRetention || {
        status: "unknown",
        policyEnabled: false,
        policyPath: "",
        autoArchiveDays: 0,
        autoPruneDays: 0,
        activeFileCount: 0,
        archivedFileCount: 0,
        archiveCandidateCount: 0,
        pruneCandidateCount: 0,
        reportPath: "",
        jsonPath: ""
      },
      evolutionProposals: payload.evolutionProposals || {
        total: 0,
        review: 0,
        accepted: 0,
        applied: 0,
        rejected: 0,
        archived: 0,
        highRisk: 0,
        staleReview: 0,
        staleAcceptedPendingApply: 0,
        oldestReviewAgeDays: null,
        oldestAcceptedAgeDays: null,
        reviewSlaDays: 7,
        acceptedApplySlaDays: 3,
        profileAdjustments: 0,
        wrapperAdjustments: 0,
        sharedSkillPromotions: 0,
        releaseEscalations: 0,
        appliedProjectProfileSelections: 0,
        appliedWrapperPromotionDrafts: 0,
        appliedSharedSkillDrafts: 0,
        appliedReleaseImpactDrafts: 0,
        appliedDraftsWithFollowUps: 0,
        followUpActionCount: 0,
        nextActionPreview: [],
        followUpDraftPreview: [],
        proposalsPath: "",
        exists: false
      },
      contextPath: payload.contextPath || ""
    };
  } catch (error) {
    return {
      available: false,
      reason: error.message
    };
  }
}

/**
 * 创建空的包装提升汇总
 */
function createEmptyWrapperPromotionSummary() {
  return {
    total: 0,
    active: 0,
    archived: 0,
    readyForRegistration: 0,
    registeredActive: 0,
    pendingFollowUps: 0,
    draftOrNeedsWork: 0
  };
}

/**
 * 收集包装提升部分
 */
export function collectWrapperPromotionSection(projectRoot, conversationMinerService) {
  const proposalsRoot = path.join(projectRoot, ".power-ai", "proposals");
  if (!fs.existsSync(proposalsRoot)) {
    return {
      available: false,
      reason: "wrapper promotion proposals root is not initialized",
      generatedAt: "",
      summary: createEmptyWrapperPromotionSummary(),
      reportPath: "",
      jsonPath: ""
    };
  }

  const audit = conversationMinerService.generateWrapperPromotionAuditReport({});
  return {
    available: true,
    generatedAt: audit.generatedAt,
    summary: audit.summary,
    reportPath: audit.reportPath,
    jsonPath: audit.jsonPath
  };
}

/**
 * 获取发布清单目录
 */
function getReleaseManifestDir(context) {
  return path.resolve(process.env.POWER_AI_RELEASE_MANIFEST_DIR || path.join(context.packageRoot, "manifest"));
}

/**
 * 收集发布治理部分
 */
export function collectReleaseSection(context, doctorReport) {
  if (doctorReport.mode !== "package-maintenance") {
    return {
      available: false,
      reason: "release summary is only collected in package-maintenance mode"
    };
  }

  const manifestRoot = getReleaseManifestDir(context);
  const versionRecord = readJsonIfExists(path.join(manifestRoot, "version-record.json"));
  const impactReport = readJsonIfExists(path.join(manifestRoot, "impact-report.json"));
  const upgradeRiskReport = readJsonIfExists(
    versionRecord?.artifacts?.upgradeRiskReportPath || path.join(manifestRoot, "upgrade-risk-report.json")
  );
  const promotionTraceReport = readJsonIfExists(
    versionRecord?.artifacts?.promotionTraceReportPath || path.join(manifestRoot, "promotion-trace-report.json")
  );
  const consumerCompatibilityMatrix = readJsonIfExists(
    versionRecord?.artifacts?.consumerCompatibilityMatrixPath || path.join(manifestRoot, "consumer-compatibility-matrix.json")
  );
  const releaseGateReport = readJsonIfExists(
    versionRecord?.artifacts?.releaseGateReportPath || path.join(manifestRoot, "release-gate-report.json")
  );
  const upgradeAdvicePackage = readJsonIfExists(
    versionRecord?.artifacts?.upgradeAdvicePackagePath || path.join(manifestRoot, "upgrade-advice-package.json")
  );
  const automationReport = readJsonIfExists(path.join(manifestRoot, "automation-report.json"));
  const notificationJsonPath = versionRecord?.artifacts?.notificationJsonPath || "";
  const notificationPayload = readJsonIfExists(notificationJsonPath);
  const releaseGroup = (doctorReport.checkGroups || []).find((group) => group.name === "release");

  return {
    available: true,
    ok: releaseGroup?.ok ?? false,
    recordedAt: versionRecord?.recordedAt || "",
    recommendedReleaseLevel: automationReport?.summary?.recommendedReleaseLevel || impactReport?.recommendedReleaseLevel || "",
    overallRiskLevel: pickHigherRiskLevel(
      upgradeRiskReport?.overallRiskLevel || "",
      upgradeAdvicePackage?.overallRiskLevel || "",
      automationReport?.summary?.overallRiskLevel || ""
    ),
    overallReleaseHint: upgradeRiskReport?.overallReleaseHint || upgradeAdvicePackage?.releaseLevel || automationReport?.summary?.recommendedReleaseLevel || "",
    changedFileCount: impactReport?.changedFiles?.length || automationReport?.summary?.changedFileCount || 0,
    affectedDomainCount: impactReport?.affectedDomainCount || automationReport?.summary?.affectedDomainCount || 0,
    affectedSkillCount: impactReport?.affectedSkillCount || automationReport?.summary?.affectedSkillCount || 0,
    impactedOwners: impactReport?.ownerSummary || [],
    followUps: impactReport?.followUps || [],
    risk: upgradeRiskReport ? {
      overallRiskLevel: upgradeRiskReport.overallRiskLevel,
      overallReleaseHint: upgradeRiskReport.overallReleaseHint,
      categoryCount: upgradeRiskReport.summary?.categoryCount || 0,
      categories: (upgradeRiskReport.categories || []).map((category) => ({
        id: category.id,
        title: category.title,
        riskLevel: category.riskLevel,
        matchedFileCount: (category.matchedFiles || []).length
      })),
      recommendedActions: upgradeRiskReport.recommendedActions || [],
      jsonPath: versionRecord?.artifacts?.upgradeRiskReportPath || path.join(manifestRoot, "upgrade-risk-report.json"),
      markdownPath: versionRecord?.artifacts?.upgradeRiskMarkdownPath || path.join(manifestRoot, "upgrade-risk-report.md")
    } : null,
    promotionTrace: promotionTraceReport ? {
      available: Boolean(promotionTraceReport.available),
      matchedRelations: promotionTraceReport.summary?.matchedRelations || 0,
      totalRelations: promotionTraceReport.summary?.totalRelations || 0,
      jsonPath: versionRecord?.artifacts?.promotionTraceReportPath || path.join(manifestRoot, "promotion-trace-report.json"),
      markdownPath: versionRecord?.artifacts?.promotionTraceMarkdownPath || path.join(manifestRoot, "promotion-trace-report.md")
    } : null,
    compatibilityMatrix: consumerCompatibilityMatrix ? {
      scenarioCount: consumerCompatibilityMatrix.summary?.totalScenarios || 0,
      passedScenarioCount: consumerCompatibilityMatrix.summary?.passedScenarios || 0,
      failedScenarioCount: consumerCompatibilityMatrix.summary?.failedScenarios || 0,
      strategies: consumerCompatibilityMatrix.summary?.strategies || [],
      jsonPath: versionRecord?.artifacts?.consumerCompatibilityMatrixPath || path.join(manifestRoot, "consumer-compatibility-matrix.json"),
      markdownPath: versionRecord?.artifacts?.consumerCompatibilityMatrixMarkdownPath || path.join(manifestRoot, "consumer-compatibility-matrix.md")
    } : null,
    releaseGates: releaseGateReport ? {
      overallStatus: releaseGateReport.overallStatus,
      failedGates: releaseGateReport.summary?.failedGates || 0,
      passedGates: releaseGateReport.summary?.passedGates || 0,
      readyForRegistration: releaseGateReport.summary?.readyForRegistration || 0,
      pendingFollowUps: releaseGateReport.summary?.pendingFollowUps || 0,
      stalledProposalCount: releaseGateReport.summary?.stalledProposalCount || 0,
      recommendedActions: releaseGateReport.recommendedActions || [],
      jsonPath: versionRecord?.artifacts?.releaseGateReportPath || path.join(manifestRoot, "release-gate-report.json"),
      markdownPath: versionRecord?.artifacts?.releaseGateMarkdownPath || path.join(manifestRoot, "release-gate-report.md")
    } : null,
    upgradeAdvice: upgradeAdvicePackage ? {
      consumerCommandCount: upgradeAdvicePackage.summary?.consumerCommandCount || 0,
      maintainerCommandCount: upgradeAdvicePackage.summary?.maintainerCommandCount || 0,
      manualCheckCount: upgradeAdvicePackage.summary?.manualCheckCount || 0,
      blockingCheckCount: upgradeAdvicePackage.summary?.blockingCheckCount || 0,
      blocked: Boolean(upgradeAdvicePackage.blocked),
      jsonPath: versionRecord?.artifacts?.upgradeAdvicePackagePath || path.join(manifestRoot, "upgrade-advice-package.json"),
      markdownPath: versionRecord?.artifacts?.upgradeAdvicePackageMarkdownPath || path.join(manifestRoot, "upgrade-advice-package.md")
    } : null,
    consumerVerification: automationReport?.consumerVerification || { skipped: true, reason: "not available" },
    notification: notificationPayload ? {
      title: notificationPayload.title || "",
      level: notificationPayload.level || "",
      jsonPath: notificationJsonPath,
      markdownPath: versionRecord?.artifacts?.notificationMarkdownPath || ""
    } : null,
    artifacts: {
      manifestRoot,
      versionRecordPath: path.join(manifestRoot, "version-record.json"),
      impactReportPath: path.join(manifestRoot, "impact-report.json"),
      upgradeRiskReportPath: versionRecord?.artifacts?.upgradeRiskReportPath || path.join(manifestRoot, "upgrade-risk-report.json"),
      promotionTraceReportPath: versionRecord?.artifacts?.promotionTraceReportPath || path.join(manifestRoot, "promotion-trace-report.json"),
      consumerCompatibilityMatrixPath: versionRecord?.artifacts?.consumerCompatibilityMatrixPath || path.join(manifestRoot, "consumer-compatibility-matrix.json"),
      automationReportPath: path.join(manifestRoot, "automation-report.json"),
      doctorReportPath: doctorReport.reportPath,
      doctorJsonPath: doctorReport.jsonPath
    }
  };
}
