import path from "node:path";

export function getProjectScanPaths({ workspaceService }) {
  const { skillsTarget, powerAiRoot } = workspaceService.getPowerAiPaths();
  const analysisRoot = path.join(powerAiRoot, "analysis");
  const reportsRoot = workspaceService.getReportsRoot();
  const overlayRoot = workspaceService.getOverlayTarget(skillsTarget);
  const autoGeneratedRoot = path.join(overlayRoot, "auto-generated");
  const manualRoot = path.join(overlayRoot, "manual");

  return {
    analysisRoot,
    reportsRoot,
    projectProfilePath: path.join(analysisRoot, "project-profile.json"),
    patternsPath: path.join(analysisRoot, "patterns.json"),
    patternReviewPath: path.join(analysisRoot, "pattern-review.json"),
    patternFeedbackPath: path.join(analysisRoot, "pattern-feedback.json"),
    patternDiffPath: path.join(analysisRoot, "pattern-diff.json"),
    patternHistoryPath: path.join(analysisRoot, "pattern-history.json"),
    componentGraphPath: path.join(analysisRoot, "component-graph.json"),
    componentPropagationPath: path.join(analysisRoot, "component-propagation.json"),
    summaryReportPath: path.join(reportsRoot, "project-scan-summary.md"),
    diffReportPath: path.join(reportsRoot, "project-scan-diff.md"),
    feedbackReportPath: path.join(reportsRoot, "project-scan-feedback.md"),
    componentGraphReportPath: path.join(reportsRoot, "component-graph-summary.md"),
    componentPropagationReportPath: path.join(reportsRoot, "component-propagation-summary.md"),
    overlayRoot,
    overlayReadmePath: path.join(overlayRoot, "README.md"),
    autoGeneratedRoot,
    manualRoot,
    autoGeneratedReadmePath: path.join(autoGeneratedRoot, "README.md")
  };
}
