import fs from "node:fs";
import path from "node:path";
import { copyDir, ensureDir, readJson, removeDirIfExists, writeJson } from "../../scripts/shared.mjs";
import {
  ensureOverlayRoot as ensureProjectScanOverlayRoot,
  getProjectScanPaths,
  loadAnalysisArtifacts as loadProjectScanArtifacts,
  writeProjectAnalysisArtifacts
} from "./analysis-artifacts.mjs";
import { buildComponentGraph, buildComponentPropagation, enrichSignalsWithComponentGraph } from "./component-graph.mjs";
import { buildAggregatedPatterns, collectPatternAggregates } from "./pattern-aggregation.mjs";
import { patternDefinitions } from "./pattern-definitions.mjs";
import { detectFilePatterns } from "./pattern-detectors.mjs";
import {
  isSupportedPatternReviewDecision,
  listSupportedPatternReviewDecisions,
  loadPatternFeedback,
  writePatternFeedback
} from "./pattern-feedback.mjs";
import { buildPatternDiff, buildPatternHistory } from "./pattern-history.mjs";
import { buildPatternReview } from "./pattern-review.mjs";
import {
  listProjectLocalSkillDirectoryNames,
  listProjectSkillSummaries,
  writeGeneratedProjectLocalSkills
} from "./project-local-skills.mjs";
import {
  buildAutoGeneratedReadme,
  buildProjectSkillMarkdown,
  buildTemplatesReference
} from "./project-local-renderers.mjs";
import { createEmptyComponentUsage, createSignals, incrementTrackedComponents } from "./signals.mjs";
import { detectRecommendedTeamProjectProfile } from "../team-policy/project-profile-detection.mjs";

const historyLimit = 20;

function readTextIfExists(filePath) {
  return fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : "";
}

function listFilesRecursively(rootDir, predicate) {
  if (!fs.existsSync(rootDir)) return [];
  const results = [];
  for (const entry of fs.readdirSync(rootDir, { withFileTypes: true })) {
    const entryPath = path.join(rootDir, entry.name);
    if (entry.isDirectory()) {
      results.push(...listFilesRecursively(entryPath, predicate));
      continue;
    }
    if (!predicate || predicate(entryPath)) results.push(entryPath);
  }
  return results;
}

export function createProjectScanService({ context, projectRoot, workspaceService, promotionTraceService }) {
  function getAnalysisPaths() {
    return getProjectScanPaths({ workspaceService });
  }

  function loadProjectPackageJson() {
    const packageJsonPath = path.join(projectRoot, "package.json");
    return fs.existsSync(packageJsonPath) ? readJson(packageJsonPath) : {};
  }

  function resolveStructure() {
    const candidates = {
      viewsRoot: "src/views",
      apiRoot: "src/api",
      routerRoot: "src/router",
      componentsRoot: "src/components",
      storeRoot: "src/store",
      utilsRoot: "src/utils"
    };
    return Object.fromEntries(
      Object.entries(candidates).map(([key, relativePath]) => [key, fs.existsSync(path.join(projectRoot, relativePath)) ? relativePath : ""])
    );
  }

  function collectFrameworkSignals(packageJson, viewFiles) {
    const dependencies = {
      ...(packageJson.dependencies || {}),
      ...(packageJson.devDependencies || {})
    };
    const joinedContent = viewFiles.map((filePath) => readTextIfExists(filePath)).join("\n");
    return {
      vue: Boolean(dependencies.vue) || viewFiles.length > 0,
      pinia: Boolean(dependencies.pinia) || fs.existsSync(path.join(projectRoot, "src", "store")),
      powerRuntime: Boolean(dependencies["@power/runtime-vue3"]) || /@power\/runtime-vue3/.test(joinedContent),
      powerComponents: Boolean(dependencies["@power/p-components"]) || /pc-table-warp|pc-dialog|PcContainer|CommonLayoutContainer|pc-layout-page-common/i.test(joinedContent)
    };
  }

  function scanProject() {
    const generatedAt = new Date().toISOString();
    const packageJson = loadProjectPackageJson();
    const structure = resolveStructure();
    const viewsRoot = structure.viewsRoot ? path.join(projectRoot, structure.viewsRoot) : "";
    const viewFiles = viewsRoot ? listFilesRecursively(viewsRoot, (filePath) => filePath.endsWith(".vue")) : [];
    const componentUsage = createEmptyComponentUsage();
    const fileRoleSummary = { page: 0, pageCandidate: 0, pageFragment: 0, dialogFragment: 0 };
    const fileAnalyses = new Map();

    for (const viewFile of viewFiles) {
      const content = readTextIfExists(viewFile);
      const relativePath = path.relative(projectRoot, viewFile).replace(/\\/g, "/");
      const signals = createSignals(relativePath, content);
      fileAnalyses.set(relativePath, signals);
      incrementTrackedComponents(componentUsage, signals.componentPresence);

      if (signals.fileRole === "page") fileRoleSummary.page += 1;
      else if (signals.fileRole === "page-candidate") fileRoleSummary.pageCandidate += 1;
      else if (signals.fileRole === "page-fragment") fileRoleSummary.pageFragment += 1;
      else if (signals.fileRole === "dialog-fragment") fileRoleSummary.dialogFragment += 1;
    }

    const componentGraph = buildComponentGraph(fileAnalyses);
    const componentPropagation = buildComponentPropagation(fileAnalyses, componentGraph);
    const enrichedFileAnalyses = enrichSignalsWithComponentGraph(fileAnalyses, componentGraph, componentPropagation);

    const aggregates = collectPatternAggregates(enrichedFileAnalyses, detectFilePatterns);
    const patterns = buildAggregatedPatterns({ aggregates, patternDefinitions });

    const frameworkSignals = collectFrameworkSignals(packageJson, viewFiles);
    const teamProjectProfileRecommendation = detectRecommendedTeamProjectProfile({
      context,
      projectRoot,
      projectProfileArtifact: {
        frameworkSignals
      }
    });

    return {
      generatedAt,
      projectProfile: {
        projectName: packageJson.name || path.basename(projectRoot),
        generatedAt,
        structure,
        frameworkSignals,
        teamProjectProfileRecommendation,
        componentUsage,
        componentGraphSummary: componentGraph.summary,
        componentPropagationSummary: componentPropagation.summary,
        fileRoleSummary,
        pagePatterns: {
          basicListPage: patterns.find((pattern) => pattern.type === "basic-list-page")?.frequency || 0,
          treeListPage: patterns.find((pattern) => pattern.type === "tree-list-page")?.frequency || 0,
          detailPage: patterns.find((pattern) => pattern.type === "detail-page")?.frequency || 0,
          dialogFormCrud: patterns.find((pattern) => pattern.type === "dialog-form")?.frequency || 0
        },
        fileSummary: { viewFileCount: viewFiles.length }
      },
      patterns: { generatedAt, patterns },
      componentGraph,
      componentPropagation
    };
  }

  function loadPersistedPatternFeedback(paths = getAnalysisPaths()) {
    return loadPatternFeedback(paths.patternFeedbackPath);
  }

  function buildAnalysisOutputs({ paths, result, patternFeedback }) {
    const previousPatterns = fs.existsSync(paths.patternsPath) ? readJson(paths.patternsPath) : { patterns: [] };
    const previousPatternReview = fs.existsSync(paths.patternReviewPath) ? readJson(paths.patternReviewPath) : { patterns: [] };
    const previousPatternHistory = fs.existsSync(paths.patternHistoryPath) ? readJson(paths.patternHistoryPath) : { snapshots: [] };
    const patternReview = buildPatternReview(result.patterns.patterns, { feedback: patternFeedback });
    const patternDiff = buildPatternDiff({
      previousPatterns,
      previousReview: previousPatternReview,
      currentPatterns: result.patterns,
      currentReview: patternReview,
      currentGeneratedAt: result.generatedAt
    });
    const patternHistory = buildPatternHistory({
      previousHistory: previousPatternHistory,
      projectName: result.projectProfile.projectName,
      generatedAt: result.generatedAt,
      patterns: result.patterns,
      patternReview,
      historyLimit
    });

    return {
      patternReview,
      patternDiff,
      patternHistory,
      outputs: writeProjectAnalysisArtifacts({
        paths,
        result,
        patternReview,
        patternFeedback,
        patternDiff,
        patternHistory
      })
    };
  }

  function writeProjectAnalysis() {
    const paths = getAnalysisPaths();
    const result = scanProject();
    const patternFeedback = loadPersistedPatternFeedback(paths);
    const {
      patternReview,
      patternDiff,
      patternHistory,
      outputs
    } = buildAnalysisOutputs({ paths, result, patternFeedback });

    return {
      ...result,
      patternFeedback,
      patternReview,
      patternDiff,
      patternHistory,
      outputs
    };
  }

  function loadAnalysisArtifacts() {
    return loadProjectScanArtifacts(getAnalysisPaths());
  }

  function ensureOverlayRoot(paths) {
    return ensureProjectScanOverlayRoot(paths);
  }

  function generateProjectLocalSkills({ regenerate = false } = {}) {
    const paths = getAnalysisPaths();
    const analysisArtifacts = loadAnalysisArtifacts();
    ensureOverlayRoot(paths);
    if (regenerate) removeDirIfExists(paths.autoGeneratedRoot);
    const generationDetails = writeGeneratedProjectLocalSkills({
      paths,
      analysisArtifacts,
      patternDefinitions,
      renderSkillMarkdown: buildProjectSkillMarkdown,
      renderTemplatesReference: buildTemplatesReference,
      renderAutoGeneratedReadme: buildAutoGeneratedReadme
    });

    return {
      generatedAt: analysisArtifacts.patterns.generatedAt,
      projectName: analysisArtifacts.projectProfile.projectName,
      ...generationDetails,
      skipped: generationDetails.createdSkillNames.length === 0
        && generationDetails.updatedSkillNames.length === 0
        && generationDetails.removedSkillNames.length === 0
        && !generationDetails.readmeUpdated,
      reason: generationDetails.createdSkillNames.length === 0
        && generationDetails.updatedSkillNames.length === 0
        && generationDetails.removedSkillNames.length === 0
        && !generationDetails.readmeUpdated
        ? "auto-generated skills already up to date"
        : "",
      regenerated: regenerate,
      patternReview: analysisArtifacts.patternReview
    };
  }

  function listProjectLocalSkills() {
    const paths = getAnalysisPaths();
    ensureOverlayRoot(paths);
    const autoGeneratedSkills = fs.existsSync(paths.autoGeneratedRoot)
      ? listProjectSkillSummaries(paths.autoGeneratedRoot, "auto-generated")
      : [];
    const manualSkills = fs.existsSync(paths.manualRoot)
      ? listProjectSkillSummaries(paths.manualRoot, "manual")
      : [];
    return {
      projectName: loadProjectPackageJson().name || path.basename(projectRoot),
      manualSkills,
      autoGeneratedSkills
    };
  }

  function promoteProjectLocalSkill({ skillName, force = false } = {}) {
    if (!skillName) throw new Error("promote-project-local-skill requires a skill name.");
    const paths = getAnalysisPaths();
    const sourceRoot = path.join(paths.autoGeneratedRoot, skillName);
    const targetRoot = path.join(paths.manualRoot, skillName);
    if (!fs.existsSync(sourceRoot)) throw new Error(`Auto-generated skill not found: ${skillName}`);
    if (fs.existsSync(targetRoot) && !force) throw new Error(`Manual project-local skill already exists: ${skillName}. Use --force to overwrite.`);

    ensureOverlayRoot(paths);
    ensureDir(paths.manualRoot);
    if (fs.existsSync(targetRoot)) removeDirIfExists(targetRoot);
    copyDir(sourceRoot, targetRoot);

    const metaPath = path.join(targetRoot, "skill.meta.json");
    const meta = fs.existsSync(metaPath) ? readJson(metaPath) : { name: skillName };
    const promotedAt = new Date().toISOString();
    writeJson(metaPath, {
      ...meta,
      status: "active",
      source: "manual-promoted",
      promotedAt,
      promotedFrom: `auto-generated/${skillName}`
    });

    promotionTraceService?.recordRelation({
      relationType: "project-skill->manual-project-skill",
      source: {
        type: "project-skill",
        id: skillName,
        path: sourceRoot
      },
      target: {
        type: "manual-project-skill",
        id: skillName,
        path: targetRoot
      },
      metadata: {
        promotedAt,
        promotedFrom: `auto-generated/${skillName}`,
        patternId: meta.patternId || "",
        projectName: loadProjectPackageJson().name || path.basename(projectRoot)
      },
      recordedAt: promotedAt
    });

    return {
      skillName,
      promotedAt,
      sourceRoot,
      targetRoot
    };
  }

  function resolveReviewedPattern(patternIdOrType, patterns) {
    return patterns.find((pattern) => pattern.id === patternIdOrType || pattern.type === patternIdOrType);
  }

  function reviewProjectPattern({ patternId, decision, note = "", clear = false } = {}) {
    if (!patternId) throw new Error("review-project-pattern requires a pattern id or pattern type.");
    if (clear && decision) throw new Error("review-project-pattern cannot use --clear together with --decision.");
    if (!clear && !decision) throw new Error("review-project-pattern requires --decision unless --clear is used.");
    if (decision && !isSupportedPatternReviewDecision(decision)) {
      throw new Error(`Unsupported pattern review decision: ${decision}. Supported: ${listSupportedPatternReviewDecisions().join(", ")}.`);
    }

    const paths = getAnalysisPaths();
    const currentScan = scanProject();
    const reviewedPattern = resolveReviewedPattern(patternId, currentScan.patterns.patterns);
    if (!reviewedPattern) throw new Error(`Pattern not found in current project scan: ${patternId}`);

    const existingFeedback = loadPersistedPatternFeedback(paths);
    const now = new Date().toISOString();
    const existingOverride = (existingFeedback.overrides || []).find((item) => item.patternId === reviewedPattern.id);
    const remainingOverrides = (existingFeedback.overrides || []).filter((item) => item.patternId !== reviewedPattern.id);

    const nextFeedback = clear
      ? {
        ...existingFeedback,
        overrides: remainingOverrides
      }
      : {
        ...existingFeedback,
        overrides: [
          ...remainingOverrides,
          {
            patternId: reviewedPattern.id,
            patternType: reviewedPattern.type,
            decision,
            note,
            createdAt: existingOverride?.createdAt || now,
            updatedAt: now
          }
        ]
      };

    const patternFeedback = writePatternFeedback(paths.patternFeedbackPath, nextFeedback);
    const result = scanProject();
    const analysisOutputs = buildAnalysisOutputs({ paths, result, patternFeedback });

    return {
      patternId: reviewedPattern.id,
      patternType: reviewedPattern.type,
      cleared: clear,
      decision: clear ? "" : decision,
      note: clear ? "" : note,
      patternFeedback,
      patternFeedbackPath: paths.patternFeedbackPath,
      feedbackReportPath: paths.feedbackReportPath,
      currentReview: analysisOutputs.patternReview.patterns.find((item) => item.id === reviewedPattern.id) || null,
      outputs: analysisOutputs.outputs
    };
  }

  function runProjectScanPipeline({ regenerate = false } = {}) {
    const scanResult = writeProjectAnalysis();
    const generationResult = generateProjectLocalSkills({ regenerate });
    return { scanResult, generationResult };
  }

  return {
    getAnalysisPaths,
    scanProject,
    writeProjectAnalysis,
    loadAnalysisArtifacts,
    generateProjectLocalSkills,
    listProjectLocalSkills,
    promoteProjectLocalSkill,
    reviewProjectPattern,
    runProjectScanPipeline
  };
}
